export const dummySubject: subject[] = [
  {
      id: "1",
      name: "Metoda Pemrograman Modern",
      room: "B. 306",
      startTime: "10:00 PM",
      endTime: "12:00 PM",
      lecturer: ["Dr. John Doe", "Jane Smith"],
      meeting: ["Zoom", "Google Meet"],
      category: "High",
  },
  {
      id: "2",
      name: "Keamanan Jaringan",
      room: "B. 206",
      startTime: "07:30 PM",
      endTime: "09:30 PM",
      lecturer: ["Ir. Joko Susilo", "Dewi Lestari"],
      meeting: ["Zoom", "Google Meet"],
  },
  {
      id: "3",
      name: "Big Data dan Analisis",
      room: "B. 204",
      startTime: "10:00 PM",
      endTime: "12:00 PM",
      lecturer: ["Dr. John Doe"],
      meeting: ["Zoom", "Google Meet"],
      category: "High",
  },
  {
      id: "4",
      name: "Manajemen Ekonomi Teknik",
      room: "B. 206",
      startTime: "07:30 PM",
      endTime: "09:30 PM",
      lecturer: ["Dewi Lestari"],
      meeting: ["Zoom", "Google Meet"],
  },
];
