export const dummySubject: subject[] = [
  {
    id: "1",
    name: "Kriptografi",
    room: "B. 306",
    day: "Monday",
    startTime: "10:00 PM",
    endTime: "12:10 PM",
    lecturer: ["Pak Eko", "Pak Arfan"],
    meeting: ["Zoom", "Google Meet"],
    category: "High",
  },
  {
    id: "2",
    name: "Keamanan Jaringan",
    room: "B. 206",
    day: "Tuesday",
    startTime: "07:30 PM",
    endTime: "09:10 PM",
    lecturer: ["Pak Yos", "Pak Arfan"],
    meeting: ["Zoom", "Google Meet"],
  },
  {
    id: "4",
    name: "Prak. Rekayasa Perangkat Lunak",
    room: "Lab Kom",
    day: "Tuesday",
    startTime: "12:40 PM",
    endTime: "15:30 PM",
    lecturer: ["Pak Maman"],
    meeting: ["Zoom", "Google Meet"],
    category: "High",
  },
  {
    id: "4",
    name: "Prak. Jaringan Komputer",
    room: "Lab Kom",
    day: "Wednesday",
    startTime: "15:30 PM",
    endTime: "18:21 PM",
    lecturer: ["Pak yos"],
    meeting: ["Zoom", "Google Meet"],
  },
  {
    id: "5",
    name: "Jaringan Komputer",
    room: "Lab Kom",
    day: "Thursday",
    startTime: "13:00 PM",
    endTime: "14:30 PM",
    lecturer: ["Pak yos"],
    meeting: ["Zoom", "Google Meet"],
  },
  {
    id: "6",
    name: "Big Data Analytic",
    room: "B. 203",
    day: "Thursday",
    startTime: "15:31 PM",
    endTime: "17:11 PM",
    lecturer: ["Pak yos"],
    meeting: ["Zoom", "Google Meet"],
  },
  {
    id: "7",
    name: "Manajemen Ekonomi Teknik",
    room: "B. 305",
    day: "Friday",
    startTime: "07:30 PM",
    endTime: "09:10 PM",
    lecturer: ["Pak Jaka"],
    meeting: ["Zoom", "Google Meet"],
  },
  {
    id: "8",
    name: "Komputasi Cerdas",
    room: "B. 201",
    day: "Friday",
    startTime: "09:30 PM",
    endTime: "12:11 PM",
    lecturer: ["Pak yos"],
    meeting: ["Zoom", "Google Meet"],
  },
  {
    id: "9",
    name: "Metoda Pemrograman Modern",
    room: "B. 201",
    day: "Friday",
    startTime: "13:00 PM",
    endTime: "14:40 PM",
    lecturer: ["Pak Arfan", "Pak Maman"],
    meeting: ["Zoom", "Google Meet"],
  },
];
